version: "{build}"
image: Visual Studio 2015
clone_depth: 1
environment:
  matrix:
  - variant: release
    model: 64
    compiler: msvc-14.0
    PYTHON: "C:\\Python36-x64"

install:
  - SET PATH=%PYTHON%;%path%
  - git submodule update --init --recursive
  - set ROOT_DIRECTORY=%CD%
  - cd %ROOT_DIRECTORY%
  - if not defined compiler ( set compiler="" )
  - if not defined crypto ( set crypto=built-in )
  - if not defined linkflags ( set linkflags="" )
  - if not defined include ( set include="" )
  - cd %ROOT_DIRECTORY%
  - set BOOST_ROOT=c:\Libraries\boost_1_63_0
  - set BOOST_BUILD_PATH=%BOOST_ROOT%\tools\build
  - echo %BOOST_ROOT%
  - echo %BOOST_BUILD_PATH%
  - set PATH=%PATH%;%BOOST_BUILD_PATH%\src\engine\bin.ntx86
  - cd %ROOT_DIRECTORY%
  - set PATH=c:\msys64\mingw32\bin;%PATH%
  - g++ --version
  - python --version
  - echo %ROOT_DIRECTORY%
  - cd %BOOST_BUILD_PATH%\src\engine
  - build.bat >nul
  - cd %ROOT_DIRECTORY%

build_script:
  # python binding
  - cd %ROOT_DIRECTORY%\bindings\python
  # we use 64 bit python builds
  - >
    b2.exe --hash
    warnings=all
    warnings-as-errors=on
    -j2
    %compiler%
    address-model=%model%
    picker-debugging=on
    invariant-checks=full
    variant=%variant%
    %linkflags%
    %include%
    link=shared
    crypto=%crypto%
    libtorrent-link=shared
    stage_module
    stage_dependencies

#~ test_script:
  #~ - cd %ROOT_DIRECTORY%\bindings\python
  #~ # we use 64 bit python build
  #~ - if defined python (
    #~ copy dependencies\*.* .
    #~ & c:\Python35-x64\python.exe test.py -b
    #~ )

artifacts:
  - path: bindings\python\dist\*.whl
    name: python-wheel
  - path: bindings\python\dist\*.msi
    name: python-binding-win32
  - path: bindings\python\libtorrent*.pyd
    name: libtorrent.pyd
